version: "3.8"

services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            # Example environment variables, adjust as needed
            # - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
            - REDIS_URL=redis://redis:6379/0
        depends_on:
            redis:
                condition: service_healthy
            # - db # Uncomment if you add a database service

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
            timeout: 3s
            retries: 5

    # db: # Uncomment and configure if you need a PostgreSQL database
    #   image: postgres:13-alpine
    #   environment:
    #     POSTGRES_DB: mydatabase
    #     POSTGRES_USER: user
    #     POSTGRES_PASSWORD: password
    #   volumes:
    #     - db_data:/var/lib/postgresql/data
    #   ports:
    #     - "5432:5432"
# volumes:
#   db_data: # Uncomment if you add a database service
